# State-history endpoint to connect to (nodeos) (fill_plugin)
# fill-connect-to = 127.0.0.1:8080

# Maximum unacknowledged SHiP block messages (fill_plugin)
# fill-max-messages-in-flight = 1024

# Acknowledge SHiP messages after this many are successfully processed (fill_plugin)
# fill-ack-batch-size = 256

# Trim history before irreversible (fill_plugin)
# fill-trim = 

# Database schema (pg_plugin)
# pg-schema = chain

# Plugin(s) to enable, may be specified multiple times
# plugin = 
